# Generated by Django 3.2.23 on 2023-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='meal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='phonenumber',
            field=models.CharField(max_length=200),
        ),
    ]
